language: python

python:
  - "3.7"

before_install:
  - export TZ='Asia/Shanghai'

install:
  - pip install mkdocs==1.0.4
  - pip install pymdown-extensions==6.2.1
  - pip install mkdocs-material==4.6.0

script:
  - mkdocs build --clean
  
branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: site
  keep-history: false
  on:
    branch: master